# coding=utf-8
import re
import pymysql
import traceback
import time
from core.util import *
from core.reporter import *
def replace_var(source, aaa):
	variable_regexp = r"\${([\w_]+)"
	result = re.findall(variable_regexp, source)
	print(result)
	for r in result:
		source = source.replace('${' + r + '}', aaa)
	return source

a = 'hjkljhf'
source = '{"a":"123", "reqtid":"${eeddd}"}'
# print(replace_var(source, a))

def db_connect():
	return pymysql.connect(host='192.168.100.35', port=int('3306'), user='wangjia', password='wangjia123')

def test():
	tid = '1C0421918000215963897700078468'
	times = [0, 1]

	res = ''
	for i in times:
		connect = db_connect()
		cursor = connect.cursor()
		sql = "select charge from pccredit.zx_user_history where tid = '{ttt}'".format(ttt=tid)
		try:
			cursor.execute(sql)
			a = cursor.fetchall()[0][0]
			assert str(a) == '1', '失败'
			res = '通过'
			return res
		except IndexError:
			if i == times[-1]:
				raise Exception('没找到%s相关的记录,zuh计费校验失败' % tid)
			else:
				time.sleep(0.8)
				continue
		finally:
			cursor.close()
			connect.close()
	return res

print(test())
# try:
# 	print(test())
# except:
# 	print('==============')
# 	print(traceback.format_exc())

infos = [{'id': '验签失败-3', 'desc': '统一扣费', 'log': ['响应状态码验证通过', 'Json字段值验证通过resCode', '响应签名验证成功', '响应时间验证通过', 'zuh计费验证通过'], 'error': [], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/internal/common/charge?account=apiwangjia-mock&type=33140017&chargeType=331400171&amount=1&reqTid=${req_id}&sign=3836AE24BEED999E22E7073F9A65EE8C', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=apiwangjia-mock&type=33140017&chargeType=331400171&amount=1&reqTid=${req_id}&sign=3836AE24BEED999E22E7073F9A65EE8C', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1003\\",\\"resMsg\\":\\"\\u8d26\\u6237\\u6ca1\\u6709\\u6b64\\u63a5\\u53e3\\u8bbf\\u95ee\\u6743\\u9650\\",\\"tid\\":\\"C0422090000315964319y27597123\\",\\"reqTid\\":\\"${req_id}\\",\\"sign\\":\\"643C37159710B1F60A137DC0043E34C5\\"}"', '响应时间:44', 'cookie:{}'], 'result': 'pass'},
{'id': '验签失败-76', 'desc': '验签失败-运营商在网状态在网时长查询（手机号MD5）13090112', 'log': ['响应状态码验证通过', 'Json字段值验证通过resCode', '响应时间验证通过', 'zuh计费验证通过'], 'error': [], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/telecom/usestate/md5?account=auto_api_test&name=张三&cid=320101198301010097&mobile=81DAB6C7E2850B04CC5D9133F2821C8B&reqTid=1234&sign=415743ED20768C12F121C5792B0E3A93', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&name=张三&cid=320101198301010097&mobile=81DAB6C7E2850B04CC5D9133F2821C8B&reqTid=1234&sign=415743ED20768C12F121C5792B0E3A93', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1013\\",\\"resMsg\\":\\"\\u9a8c\\u7b7e\\u5931\\u8d25\\",\\"reqTid\\":\\"1234\\",\\"tid\\":\\"C0421309011215964319s28513285\\",\\"sign\\":\\"3A75C720EBF658807D89895A3CD157EC\\",\\"data\\":null}"', '响应时间:189', 'cookie:{}'], 'result': 'pass'}, {'id': '验签失败-91', 'desc': '验签失败-企业工商信息查询T2-API-30319001', 'log': ['响应状态码验证通过', 'Json字段值验证通过resCode', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 362, in check_zuh_charge\n    a = cursor.fetchall()[0][0]\nIndexError: tuple index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 369, in check_zuh_charge\n    raise Exception(\'没找到{tid}相关的记录,zuh计费校验失败\'.format(ttt=self.tid))\nKeyError: \'tid\'\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/corp/t2?account=auto_api_test&entName=%E4%B8%AD%E8%AF%9A%E4%BF%A1%E5%BE%81%E4%BF%A1%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&entCid=911100007725523312&creditCode=911100007725523312&reqTid=123114&sign=77A9E9FA840AA4D3D775B0F5C78ED6CA&province=110000&timeOut=180', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&entName=%E4%B8%AD%E8%AF%9A%E4%BF%A1%E5%BE%81%E4%BF%A1%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&entCid=911100007725523312&creditCode=911100007725523312&reqTid=123114&sign=77A9E9FA840AA4D3D775B0F5C78ED6CA&province=110000&timeOut=180', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1013\\",\\"resMsg\\":\\"\\u9a8c\\u7b7e\\u5931\\u8d25\\",\\"tid\\":null,\\"sign\\":\\"29F70006AE868B5D9329DA368CAB7658\\",\\"data\\":null}"', '响应时间:26', 'cookie:{}'], 'result': 'fail'},
{'id': '验签失败-109', 'desc': '验签失败-工行手机实名认证-13010196', 'log': ['响应状态码验证通过', '响应时间验证通过', 'zuh计费验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【1031】\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/telecom/identity/gh/dss', '请求方法:post', '请求头:{"Content-Type": "application/json"}', '请求正文:{}', '请求url参数:{account": "auto_api_test","data": "021a081225f349f96633060edce4aca8184157b7792e9e5df3ce7e5bd892ae414c641d4da11762b3af089a635f7e48c7b686105deccf217f8a3f76aa670200330e8b4f9b1746a38e","reqTid": "1234","sign": "8f27f6663419a40b7a5ccd243a5850b5c07fcbc0d848b192483d940b34845e33b89e238c7997c90501d291bd6233d341577534b6dc6bba69655531d649659c39c8c30592c0f5ec14270f63a6af50e96f3780048d59905dcf6665b6422c46186bff23dc2b5a8652412decc5d7b685fcb2988849d28dbf1a23614220363b0493c73a546139c04ed84b938c6e57c5afee87997bef7c211daa88ddc442d42750d7c8b5984045558d30e5f18c72196a07e62a3163db3448fee551d85ab36c4ba50f5e7faafc09b9d375d6d86b310f8f76ad8b301dfd9ce45360398e074af08e6caf5677a5f56286d6ed65b96c8c0bbdbb606a8c30e1371ed551166baaea847b8ab78c"}', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1031\\",\\"resMsg\\":\\"\\u89e3\\u5bc6\\u5931\\u8d25\\",\\"tid\\":\\"C042130101961h596431932090148\\",\\"reqTid\\":null,\\"sign\\":null,\\"data\\":null,\\"signature\\":null}"', '响应时间:34', 'cookie:{}'], 'result': 'fail'},
{'id': '验签失败-110', 'desc': '验签失败-诚信度验证评分-14110002', 'log': ['响应状态码验证通过', '响应时间验证通过', 'zuh计费验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【1012】\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/gps/addverif/gh', '请求方法:post', '请求头:{"Content-Type": "application/json"}', '请求正文:{}', '请求url参数:{account": "auto_api_test","reqTid": "1234","data": "021a081225f349f909b168c607a620aa7f80c272131f34bbd8c7473d8d22c2b5d2731b44177281b4e31232b57d725e405c1d7665259eb0e32819815d35c0895cf13398b8685113aa13260f32b42baa7f1c61457530da5c82b5d8ba75d3ad07abff5ee0c06179e66ec0ef5b187e7a39f849b4b852a8247ace2b69237daf26afd855989c6c2d7aebad9e826bb6c5b6ae3db1f562a02183c858d469e44bb0735c6499309289f449e296","sign": "8e34fbe8edad95c0c703782997e35b9ebaee4e5f63570f1e038930319fe41ac54a8a2d0a779486b037c77588beb270fe2639a780d7d90b036ca042b330a7e65764ae1274781e67b57f4ca761e06aa593c7272bbf9c366220c891e935bbff496d87ab81e241b3671807e99a41f2fc6b9fa024aca6783142bd7c5a01590f49e0c6f45239420603649dd8866d9da50097b70781936d97a9a6d733daa430f25679cdc69bc1e05d8c85c4b972f3d77cc1a24671fc79f779c62b580ad548a3f473f04c7d71b18a3658c8fa1fb8f8122940162e3385eb2bb4e7cd9dd0d1863fe6f01c16290c7961836a9bcff072aee891f297c96a3a47ad4bd944de3cad82284b135eea"}', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1012\\",\\"resMsg\\":\\"\\u53c2\\u6570\\u4e3a\\u7a7a\\u6216\\u683c\\u5f0f\\u9519\\u8bef\\",\\"reqTid\\":null,\\"tid\\":\\"C0421411000215964319338398f42\\",\\"sign\\":null,\\"data\\":null,\\"signature\\":null}"', '响应时间:45', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-115', 'desc': '验签失败-运营商基本信息查询01-无签名-13310101', 'log': ['响应状态码验证通过', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【1012】\n', 'Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 277, in get_response_json_value\n    return jsonpath.jsonpath(self.resp.json(), json_path)[0]\nTypeError: \'bool\' object is not subscriptable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 359, in check_zuh_charge\n    sql = "select charge from pccredit.zx_user_history where tid = \'{ttt}\'".format(ttt=self.tid)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 269, in tid\n    return self.get_response_json_value(\'$.tid\')\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 279, in get_response_json_value\n    raise Exception(\'响应体不是JSON格式 或没找到{json_path}字段\'.format(json_path=json_path))\nException: 响应体不是JSON格式 或没找到$.tid字段\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/customized/01', '请求方法:post', '请求头:{"Content-Type": "application/json"}', '请求正文:{}', '请求url参数:{account":"auto_api_test", "serviceNo":"1005","reqTid":"12134567890","subReqTid":"567890","params":"{\\"name\\":\\"张三1\\",\\"cid\\":\\"320101198301010097\\",\\"mobile\\":\\"18212341234\\"}"}', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1012\\",\\"resMsg\\":\\"\\u53c2\\u6570\\u4e3a\\u7a7a\\u6216\\u683c\\u5f0f\\u9519\\u8bef\\",\\"serviceNo\\":null,\\"reqTid\\":null,\\"subReqTid\\":null,\\"data\\":null,\\"sign\\":null}"', '响应时间:17', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-117', 'desc': '验签失败-风险行为数据-19510001', 'log': ['响应状态码验证通过', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【0000】\n', 'Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 364, in check_zuh_charge\n    b=b, a=a)\nAssertionError: zuh计费校验失败，实际结果是【1】,预期是【0】\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 369, in check_zuh_charge\n    raise Exception(\'没找到{tid}相关的记录,zuh计费校验失败\'.format(ttt=self.tid))\nKeyError: \'tid\'\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/riskinfo/datascore?account=auto_api_test&name=张三&cid=320101198301010097&mobile=18212341234&reqTid=1789012345', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&name=张三&cid=320101198301010097&mobile=18212341234&reqTid=1789012345', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"0000\\",\\"resMsg\\":\\"\\u5904\\u7406\\u6210\\u529f\\",\\"tid\\":\\"C042195100011b596431934771861\\",\\"reqTid\\":\\"1789012345\\",\\"data\\":{\\"isBlack\\":1,\\"riskScore\\":28,\\"hitRule\\":\\"8\\",\\"ruleDesc\\":\\"B\\",\\"details\\":{\\"sxbzx\\":[],\\"bzx\\":[],\\"shggza\\":{\\"badInfoTypeCode\\":0,\\"blCreTime\\":\\"\\"},\\"yqsj\\":[],\\"xdzj\\":[],\\"wlfm\\":[],\\"frggsxbzx\\":[],\\"frggbzx\\":[],\\"dcfx\\":[{\\"searchTime\\":\\"\\u8fd17\\u5929\\",\\"insType\\":\\"\\u516c\\u5b89\\",\\"querytimes\\":\\"1-3\\"},{\\"searchTime\\":\\"\\u8fd17\\u5929\\",\\"insType\\":\\"\\u94f6\\u884c\\",\\"querytimes\\":\\"1-3\\"},{\\"searchTime\\":\\"\\u8fd13\\u4e2a\\u6708\\",\\"insType\\":\\"\\u516c\\u5b89\\",\\"querytimes\\":\\"1-3\\"},{\\"searchTime\\":\\"\\u8fd13\\u4e2a\\u6708\\",\\"insType\\":\\"\\u94f6\\u884c\\",\\"querytimes\\":\\"1-3\\"}]}}}"', '响应时间:121', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-166', 'desc': '验签失败-20990801', 'log': ['响应状态码验证通过', '响应时间验证通过', 'zuh计费验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【1031】\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/telecom/identity/gh/2', '请求方法:post', '请求头:{"Content-Type": "application/json"}', '请求正文:{"account": "auto_api_test", "data": "d82b68052f42e6d145315c4dc934fd2763e08492f6c61207d4be746ea01e42d687addf46ec83a608bdccac3468cbe3854665a145ba261d5b62983f9d13101d80bdf7270e10193020", "reqTid": "11234", "sign": "62c0bda4edb34ab3bf0c5b1a9ad62e92af854f1bc92dc91296146faa00f9904521adfbcb4e0cc161c57a30a7b9a856aac3719de9982ad1fde80f284ac73c866f3de3378902acca36241ff01a5d16bd99a916a254e1c2d971f42925d5f95d0b5487db3d3d79843ded9a14831d8fd4a20cd6f469b286c1ce2d2aa1d52931c24ddc5c3a358b6f00fd7dae493ee4d1ae3062e5f2ea6cc773d73a3b145f48ebea17f19b58b15e32249ad45045aff9876add8127dda71d02db8b1baa5824c689fc564e0596d5206c026a19f0b52710f384ce2b686993b95a73018640eda6f701d885047a798ec30eaccbca075c6f3275e63a7ddeaa3578a47fb0d06bde45da6f95f02a"}', '请求url参数:{}', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1031\\",\\"resMsg\\":\\"\\u89e3\\u5bc6\\u5931\\u8d25\\",\\"tid\\":\\"C042130101971596431937392v120\\",\\"reqTid\\":\\"11234\\",\\"sign\\":null,\\"data\\":null,\\"signature\\":null}"', '响应时间:34', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-172', 'desc': '验签失败-20990801', 'log': ['响应状态码验证通过', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 277, in get_response_json_value\n    return jsonpath.jsonpath(self.resp.json(), json_path)[0]\nTypeError: \'bool\' object is not subscriptable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 322, in check_response_json_value\n    result = self.get_response_json_value(json_path)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 279, in get_response_json_value\n    raise Exception(\'响应体不是JSON格式 或没找到{json_path}字段\'.format(json_path=json_path))\nException: 响应体不是JSON格式 或没找到$.resCode字段\n', 'Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 277, in get_response_json_value\n    return jsonpath.jsonpath(self.resp.json(), json_path)[0]\nTypeError: \'bool\' object is not subscriptable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 359, in check_zuh_charge\n    sql = "select charge from pccredit.zx_user_history where tid = \'{ttt}\'".format(ttt=self.tid)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 269, in tid\n    return self.get_response_json_value(\'$.tid\')\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 279, in get_response_json_value\n    raise Exception(\'响应体不是JSON格式 或没找到{json_path}字段\'.format(json_path=json_path))\nException: 响应体不是JSON格式 或没找到$.tid字段\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/telecom/identity/3mo/t1/sm2', '请求方法:post', '请求头:{"Content-Type": "application/json"}', '请求正文:{"request": {"header": {"account": "auto_api_test-mock", "reqTid": "a121345"}, "body": "1175FF4727684B86A4CD39B0D1F1E34F2054D0A736DF68A1CC87F0FA2DCF4DCFC282FAFED1EA4281055E282EB62391A83FFDF9B8866449F05D8408EF7533BA23A90AD2093A8079A6EE5CCC2E635456D72C1DC4D11FDC1C71939AD00BAB2E0E6FEBDA9A77790BB92840CC652724DEEA0AC3E07C647FCBED9C3787BF5A2139E4276C7853128842394DB344658ACB514086AA2A50F89D5DAF41176B4B2E1777FB02E49EAF", "sign": "F939DBBBEC3F649901215B1AC78DEF9A"}}', '请求url参数:{}', '响应状态码:200', '响应正文:"{\\"response\\":{\\"header\\":{\\"rspCode\\":\\"ERR_004\\",\\"rspDesc\\":\\"\\u8c03\\u7528\\u7b7e\\u540d\\u9519\\u8bef\\",\\"version\\":\\"1.0\\",\\"tid\\":\\"C04213010198159643X1938289183\\"},\\"body\\":null,\\"sign\\":\\"94DF7979F13FD32FFD9C7ED63B7AC4D7\\"}}"', '响应时间:37', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-193', 'desc': '验签失败-万象分-四维评分-18120001', 'log': ['响应状态码验证通过', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【1012】\n', 'Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 362, in check_zuh_charge\n    a = cursor.fetchall()[0][0]\nIndexError: tuple index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 369, in check_zuh_charge\n    raise Exception(\'没找到{tid}相关的记录,zuh计费校验失败\'.format(ttt=self.tid))\nKeyError: \'tid\'\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/credit/score/general/factors?account=auto_api_test&card=62220211112222333344&cid=420101198001010133&name=李四&mobile=13395636062&sign=AX24950F26B678AC7395BE8E90CE9B61', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&card=62220211112222333344&cid=420101198001010133&name=李四&mobile=13395636062&sign=AX24950F26B678AC7395BE8E90CE9B61', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1012\\",\\"resMsg\\":\\"\\u53c2\\u6570\\u4e3a\\u7a7a\\u6216\\u683c\\u5f0f\\u9519\\u8bef\\",\\"score\\":0,\\"sign\\":null,\\"factors\\":null,\\"grades\\":null,\\"tid\\":\\"C0421812000115964319383572K70\\"}"', '响应时间:18', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-197', 'desc': '验签失败-司法执行画像-个人-19090001', 'log': ['响应状态码验证通过', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【1012】\n', 'Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 362, in check_zuh_charge\n    a = cursor.fetchall()[0][0]\nIndexError: tuple index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 369, in check_zuh_charge\n    raise Exception(\'没找到{tid}相关的记录,zuh计费校验失败\'.format(ttt=self.tid))\nKeyError: \'tid\'\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/riskinfo/sxzx/t2/bx?account=auto_api_test&name=李四&cid=420101198001010133&type=1&reqTid=12341234&sign=64B49FA2C57897F9CC87923DA6EBFF51&cat=1', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&name=李四&cid=420101198001010133&type=1&reqTid=12341234&sign=64B49FA2C57897F9CC87923DA6EBFF51&cat=1', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1012\\",\\"resMsg\\":\\"\\u53c2\\u6570\\u4e3a\\u7a7a\\u6216\\u683c\\u5f0f\\u9519\\u8bef\\",\\"tid\\":null,\\"sign\\":null,\\"data\\":null}"', '响应时间:27', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-207', 'desc': '验签失败-负面信息详情查询-832', 'log': ['响应状态码验证通过', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【1012】\n', 'Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 362, in check_zuh_charge\n    a = cursor.fetchall()[0][0]\nIndexError: tuple index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 369, in check_zuh_charge\n    raise Exception(\'没找到{tid}相关的记录,zuh计费校验失败\'.format(ttt=self.tid))\nKeyError: \'tid\'\n'], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/riskinfo/countdetail?account=auto_api_test&name=张三测试有限公司&uid=', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&name=张三测试有限公司&uid=', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1012\\",\\"resMsg\\":\\"\\u53c2\\u6570\\u4e3a\\u7a7a\\u6216\\u683c\\u5f0f\\u9519\\u8bef\\",\\"data\\":null,\\"reqTid\\":null,\\"sign\\":null,\\"tid\\":null}"', '响应时间:28', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-222', 'desc': '验签失败-银行卡五要素核验-12130099', 'log': ['响应状态码验证通过', 'Json字段值验证通过resCode', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 362, in check_zuh_charge\n    a = cursor.fetchall()[0][0]\nIndexError: tuple index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 369, in check_zuh_charge\n    raise Exception(\'没找到{tid}相关的记录,zuh计费校验失败\'.format(ttt=self.tid))\nKeyError: \'tid\'\n'], 'detail': ['请求地址:http://192.168.100.42:33080/data-service/auth/factor5/sm2', '请求方法:post', '请求头:{"Content-Type": "application/json"}', '请求正文:{"account": "auto_api_test", "data": {"name": "5233AD2D731A33F3ADF036123C17DFC5B9F5FF83BE4132D2D443F9D0D5FCC7CAF9F00EF5592AA6A3D08341C2D4B568B868D01064FC45CF201BF45202CE5A09E16925ABD2823194C804665A928A498D7BC18DAB1C5B218F9C2A68291E0AB38653D92AE93470A1", "cid": "9CDF80D6941BCCDEBFC0731D3D975FF257CFB3B2585F24AB7359F984F3EC3F207B6BDB4837E625CACBF66C7F7365F36FA2201E274BA09F000FE42A6754D37F70FB02DC3919DA51C146D235682D365A787DB8100523764BAD6079F09AA4F0B261993CC8544800B993A8648E00CBB1F778EBE6", "cidType": "0", "card": "61A021B6FCE14B667C664AFAC6499DF61681FE32B09EA9904775EEDB3E84C00D2B8CFA2BF4AF33A2E3A17AFE21375A390F28AF618121D96FC2CE1E4E4BFC724E008EC790FAB9925FE57B85E3DCC74F0B00B73DC980681088F5671DED2EBA5B0DA3E8F29D36F29B3646F1578F6BF59F2B73B444", "mobile": "5CB12B09AB0B85480A2CDE6A269D7F4FE3EAD0A5C62A241B98300E38F2C2F1A8DAAACE0D55983D535F5891A9BACA41EBE696F9F789172C53AD4556CAC4B4A00CDF83D2A1BF640C80855FEC0C8DF4FB7DD5CE0A24BCD28E79AE0287BB761C3830A2F2103BB2BC4789CA4145", "cardType": "1"}, "reqTid": "1234", "sign": "A778B874CEAC05AC1BF6BCBEBE694679"}', '请求url参数:{}', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1013\\",\\"resMsg\\":\\"\\u9a8c\\u7b7e\\u5931\\u8d25\\",\\"tid\\":\\"C0421213009915964319459211n02\\",\\"sign\\":\\"A778B874CEAC05AC1BF6BCBEBE694679\\"}"', '响应时间:68', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-229', 'desc': '验签失败-持卡人风险评估标签-MD5加密-12120092', 'log': ['响应状态码验证通过', 'Json字段值验证通过resCode', '响应时间验证通过', 'zuh计费验证通过'], 'error': [], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/card/risk/md5?account=auto_api_test&name=5578590139DB7070122726BF698EB4BC&cid=2CE345FABE92EB698FDB6E097A448B32&card=621483016973958&reqTid=1234mock-100-60&sign=0698A80E13A94E7D82B38915EBD0E0D6&mobile=224DDD6E32728F6FB93CA22E831FF5B5', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&name=5578590139DB7070122726BF698EB4BC&cid=2CE345FABE92EB698FDB6E097A448B32&card=621483016973958&reqTid=1234mock-100-60&sign=0698A80E13A94E7D82B38915EBD0E0D6&mobile=224DDD6E32728F6FB93CA22E831FF5B5', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1013\\",\\"resMsg\\":\\"\\u9a8c\\u7b7e\\u5931\\u8d25\\",\\"tid\\":\\"C0421212009215964319484721F72\\",\\"reqTid\\":\\"1234mock-100-60\\",\\"sign\\":\\"BC45E2D6327CF2040294AF021A5C3934\\",\\"data\\":null}"', '响应时间:28', 'cookie:{}'], 'result': 'pass'}, {'id': '验签失败-230', 'desc': '验签失败-11010001', 'log': ['响应状态码验证通过', '响应时间验证通过'], 'error': ['Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 325, in check_response_json_value\n    \'Json字段值验证失败，期望：【%s】，实际：【%s】\' % (exp_value, result)\nAssertionError: Json字段值验证失败，期望：【1013】，实际：【2030】\n', 'Traceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 277, in get_response_json_value\n    return jsonpath.jsonpath(self.resp.json(), json_path)[0]\nTypeError: \'bool\' object is not subscriptable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 44, in wrapper\n    res = func(*arg, **kwargs)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 359, in check_zuh_charge\n    sql = "select charge from pccredit.zx_user_history where tid = \'{ttt}\'".format(ttt=self.tid)\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 269, in tid\n    return self.get_response_json_value(\'$.tid\')\n  File "E:\\personal\\project\\WJ_API\\core\\client.py", line 279, in get_response_json_value\n    raise Exception(\'响应体不是JSON格式 或没找到{json_path}字段\'.format(json_path=json_path))\nException: 响应体不是JSON格式 或没找到$.tid字段\n'], 'detail': ['请求地址:http://192.168.100.111:7080/data-service/api/antifraud?name=%E8%B5%B5%E4%B8%96%E5%86%B0&account=auto_api_test&sign=988E925A3F89E964C5946750B9AF097B&cid=130427198807116512&reqTid=1234123', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:name=%E8%B5%B5%E4%B8%96%E5%86%B0&account=auto_api_test&sign=988E925A3F89E964C5946750B9AF097B&cid=130427198807116512&reqTid=1234123', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"2030\\",\\"resMsg\\":\\"\\u9a8c\\u8bc1\\u6210\\u529f\\"}"', '响应时间:239', 'cookie:{}'], 'result': 'fail'}, {'id': '验签失败-237', 'desc': '验签失败-用户经济稳定性评分-15080001', 'log': ['响应状态码验证通过', 'Json字段值验证通过resCode', '响应时间验证通过', 'zuh计费验证通过'], 'error': [], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/credit/consumability?account=auto_api_test&name=张三&sign=A58E2E0B5315115EA59125672217317A&reqTid=12341234&cid=320101198301010097', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&name=张三&sign=A58E2E0B5315115EA59125672217317A&reqTid=12341234&cid=320101198301010097', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1013\\",\\"resMsg\\":\\"\\u9a8c\\u7b7e\\u5931\\u8d25\\",\\"reqTid\\":\\"12341234\\",\\"tid\\":\\"C042150800011596431Z949625428\\",\\"sign\\":\\"78D7BBE93D5BFDBA63D84B55A06F1A28\\",\\"data\\":null}"', '响应时间:25', 'cookie:{}'], 'result': 'pass'}, {'id': '验签失败-239', 'desc': '验签失败-个人消费能力标签-12120001', 'log': ['响应状态码验证通过', 'Json字段值验证通过resCode', '响应时间验证通过', 'zuh计费验证通过'], 'error': [], 'detail': ['请求地址:http://192.168.100.42:7280/data-service/personal/consumability?account=auto_api_test&name=车建&cid=130682198708153516&mobile=18603607792&sign=27B0B7856F252418F79EFDFBE3580711&reqTid=1234consumability20a', '请求方法:get', '请求头:{}', '请求正文:{}', '请求url参数:account=auto_api_test&name=车建&cid=130682198708153516&mobile=18603607792&sign=27B0B7856F252418F79EFDFBE3580711&reqTid=1234consumability20a', '响应状态码:200', '响应正文:"{\\"resCode\\":\\"1013\\",\\"resMsg\\":\\"\\u9a8c\\u7b7e\\u5931\\u8d25\\",\\"reqTid\\":\\"1234consumability20a\\",\\"tid\\":\\"C0421509000115964319505P21694\\",\\"sign\\":\\"C7E16A2B319B20715ECAAD2554A14467\\",\\"data\\":null}"', '响应时间:37', 'cookie:{}'], 'result': 'pass'}]
Config.GLOBAL_DATA = get_gloable_data('全局变量')
# create_report(duration=23.83, start_time=time.time(), infos=infos, name='-'.join(['验签失败']))


str = r"\u5904\u7406\u6210\u529f"
str = str.encode('ascii').decode('unicode-escape')
# print(str)



# 企业微信 基础信息
AgentId = '1000002'
Secret = 'AAJS396VSKCCtjzQEjKZNGuGV1lr-wvVyFBgga8lkpo'
CorpId = 'ww38c6e8bad63f7560'
